---
# tasks file for roles/proxy

- name: Launching proxy
  docker_container:
    name: httpd
    state: started
    image: marcllopcpe/httpd:latest
    published_ports:
      - "80:80"
      - "8080:8080"
    networks:
      - name: "app-network"
